services:
  - type: web
    name: Simantap
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: local
      - key: APP_KEY
        value: (isi nanti setelah deploy pertama)
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1 # contoh: mysql.render.com atau IP
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: laravel_inertia_react
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: 123
